In [2]:
import torch

In [10]:
a = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
b = torch.tensor([[7,10],
                  [8,11],
                  [9,12]]).T # transposed

torch.mm(a,b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [11]:
# Find the min max mean sum (tensor aggregation)

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
try:
    y = torch.mean(x)
except RuntimeError as e:
    print(e)

z = torch.mean(x.type(torch.float32))
# print(z)

rand_tensor = torch.rand(3,3)
arg = torch.argmin(rand_tensor) # find the POSITION in tensor that hias min value with argmin
print(rand_tensor)
print(arg) # for nd arrays it flattens the array, if no axis is specified.


mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor([[0.0732, 0.6118, 0.1433],
        [0.8185, 0.1660, 0.1044],
        [0.2663, 0.9620, 0.4651]])
tensor(0)


In [ ]:
# reshaping - reshapes input etensor to a defined shape
# returns view of input tensor but keep the same memory as original
# stack --> vstack, hstack to combine multkple tensors
# squeeze removes all 1 dimensions from a tensor
# unsqueeze
# permute - return a view with dimensions permuted in some way.

In [35]:
x = torch.arange(1.,10.)
x, x.shape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

# change view 
z = x.view(1,9)
z,z.shape

# changing z changes x because they share the same underlying memory 
x = torch.stack([x,x,x],dim=0)
x


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [61]:
x = torch.tensor([[1,2,3,4,5,6,7]], dtype=torch.float32)
x = x.squeeze()
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [63]:
x.unsqueeze(dim=1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])

In [65]:
x_ori = torch.rand(size=(224,224,3))
x_permuted = x_ori.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
x_ori

tensor([[[0.3250, 0.2429, 0.7514],
         [0.9503, 0.7913, 0.7512],
         [0.4087, 0.7426, 0.4522],
         ...,
         [0.2709, 0.1351, 0.9051],
         [0.6959, 0.8442, 0.0909],
         [0.3345, 0.8435, 0.7566]],

        [[0.3956, 0.0790, 0.7129],
         [0.4732, 0.5424, 0.0358],
         [0.3056, 0.5847, 0.6390],
         ...,
         [0.0132, 0.2523, 0.2055],
         [0.7829, 0.7802, 0.4393],
         [0.7086, 0.3715, 0.5788]],

        [[0.1046, 0.4171, 0.5705],
         [0.8626, 0.9808, 0.8428],
         [0.9548, 0.7249, 0.5164],
         ...,
         [0.7302, 0.0485, 0.4786],
         [0.1145, 0.9048, 0.3317],
         [0.3166, 0.6589, 0.4174]],

        ...,

        [[0.0580, 0.1241, 0.1869],
         [0.3697, 0.3328, 0.4620],
         [0.0257, 0.1942, 0.7322],
         ...,
         [0.8622, 0.3394, 0.7384],
         [0.0084, 0.0332, 0.4968],
         [0.4119, 0.0995, 0.2165]],

        [[0.5572, 0.9640, 0.7800],
         [0.8617, 0.5282, 0.5493],
         [0.

In [ ]:
# indexing
# selecting data from tensors
# index with pytorch is same with indexing with numpy

In [66]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [68]:
# index on the new tensor
x[0] # 0th index of the outermost

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
x[0][0]
# middle bracket

tensor([1, 2, 3])

In [72]:
## Indexing on the inner bracket
x[0][0][2]
# out of 
#(1, 3, 3) <-- shape

tensor(1)

In [83]:
x
x[:, 1]
#all, 1, X, kinda like a wildcard.

tensor([[4, 5, 6]])

In [82]:
x[:, :, 1]
# slightly different from x[0,0,1] beacuse the colon adds a list

tensor([[2, 5, 8]])

In [85]:
x[0,0,:]

tensor([1, 2, 3])

## Pytorch and numpy
numpy and pytorch can interact with each other
cast from ndarray to tensor --> torch.from_numpy(ndarray)
cast tensor to numpy with numpy


In [91]:
import torch
import numpy as np

array = np.arange(1,10,1,dtype=np.float32)

tensor = torch.from_numpy(array) # when converting from np to torch python defaults to default np64 bit unless otherwise specified
tensor


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [93]:
back_to_array = tensor.numpy()

back_to_array.dtype

dtype('float32')

Pytorch reproducibility (taking randomness out of random using seed)

In [ ]:
RANDOM_SEED = 1001
# need to set the manual seed for every function call

torch.manual_seed(RANDOM_SEED)
rand_a = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_b = torch.rand(3,4)

rand_a, rand_b

In [96]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [97]:
# Putting tensors and models on the GPU
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [98]:
tensor_on_gpu = tensor.to(device) # init such that device uses GPU if avail

In [101]:
# if tensor is on GPU cant transform it to numpy
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])